name: "TrainRun4" # Change this
model_name: "yolo11m.pt"
class_names_path: /users/PAS2926/inolan/bv2425ObjectDetection/ShapeModel/Training/data.yaml # /Training/data.yaml
img_size: 1920
pretrained_bool: True
cos_lr_bool: True
learning_rate_initial: 0.0003
learning_rate_final: 0.0006
num_epochs: 30
batch_size: 32
gpu_id: [0,1]
patience_time: 5
validation_bool: True
num_workers: 1 # May want to change this
